packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@payloadcms/db-postgres': 3.90.2
  '@payloadcms/email-resend': 3.90.2
  '@payloadcms/live-preview-react': 3.90.2
  '@payloadcms/next': 3.90.2
  '@payloadcms/plugin-form-builder': 3.90.2
  '@payloadcms/plugin-multi-tenant': 3.90.2
  '@payloadcms/richtext-lexical': 3.90.2
  '@payloadcms/storage-vercel-blob': 3.90.2
  '@payloadcms/ui': 3.90.2
  next: ~15.4.11
  payload: 3.90.2
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.8.3
  vitest: 3.2.7
