/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    'past-events': PastEvent;
    newsletters: Newsletter;
    vacancies: Vacancy;
    speakers: Speaker;
    authors: Author;
    tags: Tag;
    media: Media;
    redirects: Redirect;
    'site-settings': SiteSetting;
    users: User;
    tenants: Tenant;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'past-events': PastEventsSelect<false> | PastEventsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Last part of the URL in this language. The home page uses "home".
   */
  slug: string;
  parent?: (number | null) | Page;
  /**
   * Full URL path. Set automatically.
   */
  path?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | HeroBlock
        | EventsCalendarPreviewBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
      )[]
    | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  /**
   * Public origin of this site, for example https://www.example.org
   */
  siteUrl: string;
  /**
   * Shared secret the other site sends when it asks this site to refresh its cache.
   */
  revalidateSecret: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  headline?: string | null;
  tagline?: string | null;
  actions?:
    | {
        label?: string | null;
        type?: ('button' | 'link') | null;
        icon?: {
          /**
           * Lucide icon name, for example ArrowRight.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: {
    src?: (number | null) | Media;
    alt?: string | null;
    /**
     * For YouTube, use the embed version of the URL.
     */
    videoUrl?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  /**
   * Original /uploads path. Old links redirect from here.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarPreviewBlock".
 */
export interface EventsCalendarPreviewBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  /**
   * Optional. Defaults to the translated title.
   */
  title?: string | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsCalendarPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  text?: string | null;
  url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  title?: string | null;
  description?: string | null;
  items?:
    | {
        icon?: {
          /**
           * Lucide icon name, for example ArrowRight.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        title?: string | null;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  title?: string | null;
  description?: string | null;
  stats?:
    | {
        stat?: string | null;
        type?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  title?: string | null;
  description?: string | null;
  actions?:
    | {
        label?: string | null;
        type?: ('button' | 'link') | null;
        icon?: {
          /**
           * Lucide icon name, for example ArrowRight.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  title?: string | null;
  description?: string | null;
  testimonials?:
    | {
        quote?: string | null;
        author?: string | null;
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  color?: ('default' | 'tint' | 'primary') | null;
  url?: string | null;
  autoPlay?: boolean | null;
  loop?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  /**
   * Tailwind background class, for example bg-background or bg-[#44AD39]/10.
   */
  background?: string | null;
  image?: {
    src?: (number | null) | Media;
    alt?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?: ('image-left' | 'image-right' | 'image-center' | 'text-above-center' | 'text-below-center') | null;
  imageSize?: ('small' | 'medium' | 'large') | null;
  verticalAlignment?: ('top' | 'center' | 'bottom') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Leave empty to show in both languages.
   */
  language?: ('en' | 'nl') | null;
  description?: string | null;
  location?: {
    address?: string | null;
    mapsLink?: string | null;
    callLink?: string | null;
  };
  startDate: string;
  endDate?: string | null;
  eventType: 'talk' | 'workshop' | 'lecture' | 'meeting' | 'board-meeting' | 'soup-kitchen' | 'csa' | 'excursion';
  speakers?:
    | {
        speaker?: (number | null) | Speaker;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Type the link text, select it, and add the registration URL as a link.
   */
  registrationLink?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  avatar?: (number | null) | Media;
  affiliation?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-events".
 */
export interface PastEvent {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Leave empty to show in both languages.
   */
  language?: ('en' | 'nl') | null;
  heroImg?: (number | null) | Media;
  excerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Author;
  date: string;
  relatedEvent?: (number | null) | Event;
  tags?: (number | Tag)[] | null;
  blocks?:
    | (
        | HeroBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
      )[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  avatar?: (number | null) | Media;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Leave empty to show in both languages.
   */
  language?: ('en' | 'nl') | null;
  type: 'article' | 'link' | 'event' | 'update';
  organization: 'Boerengroep' | 'Inspringtheater' | 'friends';
  publishDate: string;
  tags?: string[] | null;
  externalLink?: string | null;
  linkDescription?: string | null;
  author?: (number | null) | Speaker;
  featuredImage?: (number | null) | Media;
  excerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?:
    | (
        | HeroBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
      )[]
    | null;
  featured?: boolean | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Leave empty to show in both languages.
   */
  language?: ('en' | 'nl') | null;
  opportunityType: 'volunteer' | 'internship' | 'coordinator' | 'board' | 'other';
  location?: {
    type?: ('remote' | 'in-person' | 'hybrid') | null;
    cityRegion?: string | null;
  };
  startDate?: string | null;
  duration?: string | null;
  openApplication?: boolean | null;
  applicationDeadline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requiredSkills?: string[] | null;
  preferredQualities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  languagesRequired?: string[] | null;
  compensation?: {
    details?: string | null;
  };
  accessibilityNotes?: string | null;
  howToApply?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactInfo?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  supportingDocument?: (number | null) | Media;
  valuesStatement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openToNontraditional?: boolean | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  from: string;
  to: string;
  permanent?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  header: {
    logo?: (number | null) | Media;
    logoAlt: string;
    name: string;
    color?: ('default' | 'primary') | null;
    nav?:
      | {
          /**
           * Preferred. The link follows the page when its URL changes.
           */
          page?: (number | null) | Page;
          href?: string | null;
          label?: string | null;
          labelText?: string | null;
          submenu?:
            | {
                /**
                 * Preferred. The link follows the page when its URL changes.
                 */
                page?: (number | null) | Page;
                href?: string | null;
                label?: string | null;
                labelText?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  homepage?: {
    showCalendarWidget?: boolean | null;
  };
  footer?: {
    social?:
      | {
          platform: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    quickLinks?:
      | {
          title: string;
          links?:
            | {
                /**
                 * Preferred. The link follows the page when its URL changes.
                 */
                page?: (number | null) | Page;
                href?: string | null;
                label?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  theme?: {
    color?: string | null;
    font?: ('sans' | 'nunito' | 'lato') | null;
    darkMode?: ('system' | 'light' | 'dark') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('super-admin' | 'user')[];
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'editor')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'past-events';
        value: number | PastEvent;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: number | Vacancy;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  parent?: T;
  path?: T;
  body?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        eventsCalendarPreview?: T | EventsCalendarPreviewBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
      };
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  background?: T;
  headline?: T;
  tagline?: T;
  actions?:
    | T
    | {
        label?: T;
        type?: T;
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        link?: T;
        id?: T;
      };
  image?:
    | T
    | {
        src?: T;
        alt?: T;
        videoUrl?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarPreviewBlock_select".
 */
export interface EventsCalendarPreviewBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  background?: T;
  text?: T;
  url?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  items?:
    | T
    | {
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  stats?:
    | T
    | {
        stat?: T;
        type?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  actions?:
    | T
    | {
        label?: T;
        type?: T;
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  background?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  background?: T;
  color?: T;
  url?: T;
  autoPlay?: T;
  loop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  background?: T;
  image?:
    | T
    | {
        src?: T;
        alt?: T;
      };
  content?: T;
  layout?: T;
  imageSize?: T;
  verticalAlignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  description?: T;
  location?:
    | T
    | {
        address?: T;
        mapsLink?: T;
        callLink?: T;
      };
  startDate?: T;
  endDate?: T;
  eventType?: T;
  speakers?:
    | T
    | {
        speaker?: T;
        role?: T;
        id?: T;
      };
  image?: T;
  coverImage?: T;
  featured?: T;
  registrationLink?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-events_select".
 */
export interface PastEventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  heroImg?: T;
  excerpt?: T;
  author?: T;
  date?: T;
  relatedEvent?: T;
  tags?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
      };
  body?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  type?: T;
  organization?: T;
  publishDate?: T;
  tags?: T;
  externalLink?: T;
  linkDescription?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  body?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
      };
  featured?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  opportunityType?: T;
  location?:
    | T
    | {
        type?: T;
        cityRegion?: T;
      };
  startDate?: T;
  duration?: T;
  openApplication?: T;
  applicationDeadline?: T;
  description?: T;
  responsibilities?: T;
  requiredSkills?: T;
  preferredQualities?: T;
  languagesRequired?: T;
  compensation?:
    | T
    | {
        details?: T;
      };
  accessibilityNotes?: T;
  howToApply?: T;
  contactInfo?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  supportingDocument?: T;
  valuesStatement?: T;
  openToNontraditional?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  avatar?: T;
  affiliation?: T;
  bio?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  avatar?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  from?: T;
  to?: T;
  permanent?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  header?:
    | T
    | {
        logo?: T;
        logoAlt?: T;
        name?: T;
        color?: T;
        nav?:
          | T
          | {
              page?: T;
              href?: T;
              label?: T;
              labelText?: T;
              submenu?:
                | T
                | {
                    page?: T;
                    href?: T;
                    label?: T;
                    labelText?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  homepage?:
    | T
    | {
        showCalendarWidget?: T;
      };
  footer?:
    | T
    | {
        social?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        quickLinks?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    page?: T;
                    href?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  theme?:
    | T
    | {
        color?: T;
        font?: T;
        darkMode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteUrl?: T;
  revalidateSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}