/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    'past-events': PastEvent;
    newsletters: Newsletter;
    vacancies: Vacancy;
    speakers: Speaker;
    authors: Author;
    tags: Tag;
    media: Media;
    redirects: Redirect;
    'site-settings': SiteSetting;
    users: User;
    tenants: Tenant;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'past-events': PastEventsSelect<false> | PastEventsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Last part of the URL in this language. The home page uses "home".
   */
  slug: string;
  parent?: (number | null) | Page;
  /**
   * Full URL path. Set automatically.
   */
  path?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | HeroBlock
        | EventsCalendarPreviewBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
        | GalleryBlock
        | DocumentsBlock
        | PodcastBlock
        | NewsletterSignupBlock
        | FormBlock
        | ItemBlock
      )[]
    | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  /**
   * Public origin of this site, for example https://www.example.org
   */
  siteUrl: string;
  /**
   * Shared secret the other site sends when it asks this site to refresh its cache.
   */
  revalidateSecret: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  layout?: ('split' | 'centered') | null;
  headline?: string | null;
  tagline?: string | null;
  /**
   * One or two buttons are enough. The first one stands out most.
   */
  actions?:
    | {
        /**
         * Say what happens, for example "See the calendar".
         */
        label?: string | null;
        type?: ('button' | 'link') | null;
        /**
         * Optional small symbol.
         */
        icon?: {
          /**
           * Name of a Lucide icon, for example ArrowRight. See lucide.dev/icons.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        /**
         * Starts with / for this site, or https:// for another one.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: {
    src?: (number | null) | Media;
    /**
     * For people who cannot see it.
     */
    alt?: string | null;
    /**
     * Optional. A YouTube or Vimeo link. The picture is then used as the cover.
     */
    videoUrl?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Every picture and document on the site. Upload here or straight from the page you are editing. Open a picture to cut it or to choose which part must stay visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * One sentence for people who cannot see it, and for search engines.
   */
  alt?: string | null;
  /**
   * Optional. Shown under the picture in galleries. Who, what, where, or who took it.
   */
  caption?: string | null;
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarPreviewBlock".
 */
export interface EventsCalendarPreviewBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  /**
   * Optional. Without it the heading is "What's on".
   */
  title?: string | null;
  description?: string | null;
  mode?: ('upcoming' | 'type' | 'picked') | null;
  eventType?:
    ('talk' | 'workshop' | 'lecture' | 'meeting' | 'board-meeting' | 'soup-kitchen' | 'csa' | 'excursion') | null;
  events?: (number | Event)[] | null;
  count?: number | null;
  showMiniCalendar?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsCalendarPreview';
}
/**
 * Everything on the calendar. Each event gets its own page that people can share and add to their own calendar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * The last part of the event's web address. It is made for you from the title and the date. Do not change it after sharing the link.
   */
  slug?: string | null;
  /**
   * The language this is written in. Leave empty to show it to everyone.
   */
  language?: ('en' | 'nl') | null;
  /**
   * Set to Full when there are no places left. The sign-up button is then replaced by a "Fully booked" note. Cancelled events stay visible, crossed out, so people who saved them find out.
   */
  status: 'scheduled' | 'full' | 'cancelled' | 'postponed';
  /**
   * Optional. For example "Waiting list: mail us" or the new date.
   */
  statusNote?: string | null;
  /**
   * What happens, who it is for, what to bring. A new line starts a new paragraph.
   */
  description?: string | null;
  /**
   * Dutch time.
   */
  startDate: string;
  /**
   * Optional. Without it the event is shown as two hours long in people's calendars.
   */
  endDate?: string | null;
  /**
   * Sets the colour on the calendar and lets visitors filter.
   */
  eventType: 'talk' | 'workshop' | 'lecture' | 'meeting' | 'board-meeting' | 'soup-kitchen' | 'csa' | 'excursion';
  location?: {
    /**
     * Name and address, as you would say it to a friend.
     */
    address?: string | null;
    /**
     * Optional. Without it a map link is made from the place.
     */
    mapsLink?: string | null;
    /**
     * For online or hybrid events.
     */
    callLink?: string | null;
  };
  /**
   * A poster or photo. After uploading you can choose which part stays visible when the picture is cut to fit.
   */
  image?: (number | null) | Media;
  speakers?:
    | {
        speaker?: (number | null) | Speaker;
        /**
         * For example "host" or "speaker".
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Type what people should click, select it, and add the link to your sign-up form. Leave empty if people can just come.
   */
  registrationLink?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Spotlighted events are shown first and larger.
   */
  featured?: boolean | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  avatar?: (number | null) | Media;
  affiliation?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  text?: string | null;
  url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  description?: string | null;
  items?:
    | {
        /**
         * Optional small symbol.
         */
        icon?: {
          /**
           * Name of a Lucide icon, for example ArrowRight. See lucide.dev/icons.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        title?: string | null;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  description?: string | null;
  stats?:
    | {
        /**
         * For example 55 or 1.200.
         */
        stat?: string | null;
        type?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  title?: string | null;
  description?: string | null;
  /**
   * One or two buttons are enough. The first one stands out most.
   */
  actions?:
    | {
        /**
         * Say what happens, for example "See the calendar".
         */
        label?: string | null;
        type?: ('button' | 'link') | null;
        /**
         * Optional small symbol.
         */
        icon?: {
          /**
           * Name of a Lucide icon, for example ArrowRight. See lucide.dev/icons.
           */
          name?: string | null;
          color?: string | null;
          style?: string | null;
        };
        /**
         * Starts with / for this site, or https:// for another one.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  /**
   * Reading width is the most comfortable for longer texts.
   */
  width?: ('narrow' | 'normal' | 'wide') | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  description?: string | null;
  testimonials?:
    | {
        quote?: string | null;
        author?: string | null;
        /**
         * For example "farmer in Renkum".
         */
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  color?: ('default' | 'tint' | 'primary') | null;
  /**
   * For example https://www.youtube.com/watch?v=... or https://vimeo.com/...
   */
  url?: string | null;
  caption?: string | null;
  /**
   * Optional. Shown before the video plays. Without it the video's own cover is used.
   */
  poster?: (number | null) | Media;
  autoPlay?: boolean | null;
  loop?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  image?: {
    src?: (number | null) | Media;
    /**
     * For people who cannot see it.
     */
    alt?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?: ('image-left' | 'image-right' | 'image-center' | 'text-above-center' | 'text-below-center') | null;
  imageSize?: ('small' | 'medium' | 'large') | null;
  verticalAlignment?: ('top' | 'center' | 'bottom') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  source?: ('pictures' | 'pastEvent') | null;
  /**
   * Drop several photos at once. Drag to change the order. Add a caption by opening a photo.
   */
  images?: (number | Media)[] | null;
  /**
   * The gallery links back to the story of this event.
   */
  pastEvent?: (number | null) | PastEvent;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * Stories and photos of events that have happened. Link one to its calendar event and the two point to each other.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-events".
 */
export interface PastEvent {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * The last part of the web address. Letters, numbers and hyphens. Do not change it after sharing the link.
   */
  slug: string;
  /**
   * The language this is written in. Leave empty to show it to everyone.
   */
  language?: ('en' | 'nl') | null;
  heroImg?: (number | null) | Media;
  excerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Author;
  date: string;
  relatedEvent?: (number | null) | Event;
  tags?: (number | Tag)[] | null;
  /**
   * Drop all the photos of the day here at once. They show as a mosaic on the story, and can be reused in a Photo gallery block on any page.
   */
  photos?: (number | Media)[] | null;
  blocks?:
    | (
        | HeroBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
        | GalleryBlock
        | DocumentsBlock
        | PodcastBlock
        | FormBlock
        | ItemBlock
      )[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  avatar?: (number | null) | Media;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DocumentsBlock".
 */
export interface DocumentsBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  files?:
    | {
        file: number | Media;
        /**
         * Without it the file name is shown.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'documents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PodcastBlock".
 */
export interface PodcastBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  mode?: ('latest' | 'picked') | null;
  count?: number | null;
  /**
   * Type a few words from the title of each episode. The first episode that matches is shown.
   */
  episodes?:
    | {
        match: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'podcast';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Make or change forms under Forms in the menu on the left.
   */
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * Forms you can place on a page with the Form block or the Item block: a contact form, a sign-up, an order. You decide the questions and the message people see afterwards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemBlock".
 */
export interface ItemBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  title: string;
  /**
   * Visitors can flip through them. Three or four is plenty.
   */
  images?: (number | Media)[] | null;
  /**
   * What it is, sizes, how people get it.
   */
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Free text, for example "€15" or "pay what you can".
   */
  priceText?: string | null;
  actionType?: ('link' | 'form') | null;
  /**
   * For example "Order a shirt".
   */
  buttonLabel?: string | null;
  linkUrl?: string | null;
  /**
   * Answers arrive under Form responses.
   */
  form?: (number | null) | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'item';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  /**
   * The colour behind this section. Alternate white with a colour to give the page rhythm.
   */
  background?: ('white' | 'mist' | 'leaf' | 'harvest' | 'sky' | 'dark') | null;
  /**
   * Optional. Replaces the standard heading for this page only.
   */
  heading?: string | null;
  /**
   * Optional.
   */
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * The last part of the web address. Letters, numbers and hyphens. Do not change it after sharing the link.
   */
  slug: string;
  /**
   * The language this is written in. Leave empty to show it to everyone.
   */
  language?: ('en' | 'nl') | null;
  type: 'article' | 'link' | 'event' | 'update';
  organization: 'Boerengroep' | 'Inspringtheater' | 'friends';
  publishDate: string;
  tags?: string[] | null;
  externalLink?: string | null;
  linkDescription?: string | null;
  author?: (number | null) | Speaker;
  featuredImage?: (number | null) | Media;
  excerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?:
    | (
        | HeroBlock
        | CalloutBlock
        | FeaturesBlock
        | StatsBlock
        | CtaBlock
        | ContentBlock
        | TestimonialBlock
        | VideoBlock
        | ImageTextBlock
        | GalleryBlock
        | DocumentsBlock
        | PodcastBlock
        | FormBlock
        | ItemBlock
      )[]
    | null;
  featured?: boolean | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * The last part of the web address. Letters, numbers and hyphens. Do not change it after sharing the link.
   */
  slug: string;
  /**
   * The language this is written in. Leave empty to show it to everyone.
   */
  language?: ('en' | 'nl') | null;
  opportunityType: 'volunteer' | 'internship' | 'coordinator' | 'board' | 'other';
  location?: {
    type?: ('remote' | 'in-person' | 'hybrid') | null;
    cityRegion?: string | null;
  };
  startDate?: string | null;
  duration?: string | null;
  openApplication?: boolean | null;
  applicationDeadline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requiredSkills?: string[] | null;
  preferredQualities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  languagesRequired?: string[] | null;
  compensation?: {
    details?: string | null;
  };
  accessibilityNotes?: string | null;
  howToApply?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactInfo?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  supportingDocument?: (number | null) | Media;
  valuesStatement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openToNontraditional?: boolean | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  from: string;
  to: string;
  permanent?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The parts of the site that show on every page: name and logo, the menu, the footer, the newsletter box and the calendar options.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  general: {
    name: string;
    /**
     * A short sentence about what you do. Shown next to the logo in the footer.
     */
    tagline?: string | null;
    /**
     * Shown in the header and the footer. A wide image with a transparent background works best.
     */
    logo?: (number | null) | Media;
    /**
     * Shown in the footer. Leave a field empty to hide it.
     */
    contact?: {
      /**
       * One line per row, for example street, then postcode and town.
       */
      address?: string | null;
      email?: string | null;
      phone?: string | null;
    };
    /**
     * Shown as small links in the footer, in this order.
     */
    social?:
      | {
          platform: 'instagram' | 'facebook' | 'linkedin' | 'youtube' | 'mastodon' | 'bluesky' | 'x' | 'chat' | 'other';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  header?: {
    nav?:
      | {
          /**
           * The words people click on. Switch language at the top to fill in the other one.
           */
          label?: string | null;
          linkType?: ('page' | 'section' | 'custom') | null;
          /**
           * The link keeps working when this page is renamed or moved.
           */
          page?: (number | null) | Page;
          /**
           * Parts of the site that are always there, such as the calendar.
           */
          section?:
            | ('home' | 'calendar' | 'past-events' | 'news' | 'newsletter' | 'friends-news' | 'podcast' | 'vacancies')
            | null;
          /**
           * Starts with https:// for another website, or with / for an address on this site.
           */
          url?: string | null;
          /**
           * Optional. Jumps to one part of the page, for example "volunteers" on the vacancies page.
           */
          anchor?: string | null;
          /**
           * Use this for the one thing you most want visitors to do. One button is enough.
           */
          highlight?: boolean | null;
          /**
           * Optional. Links that appear when someone opens this menu item.
           */
          children?:
            | {
                /**
                 * The words people click on. Switch language at the top to fill in the other one.
                 */
                label?: string | null;
                linkType?: ('page' | 'section' | 'custom') | null;
                /**
                 * The link keeps working when this page is renamed or moved.
                 */
                page?: (number | null) | Page;
                /**
                 * Parts of the site that are always there, such as the calendar.
                 */
                section?:
                  | (
                      | 'home'
                      | 'calendar'
                      | 'past-events'
                      | 'news'
                      | 'newsletter'
                      | 'friends-news'
                      | 'podcast'
                      | 'vacancies'
                    )
                  | null;
                /**
                 * Starts with https:// for another website, or with / for an address on this site.
                 */
                url?: string | null;
                /**
                 * Optional. Jumps to one part of the page, for example "volunteers" on the vacancies page.
                 */
                anchor?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    /**
     * Two or three short columns read best.
     */
    columns?:
      | {
          title?: string | null;
          links?:
            | {
                /**
                 * The words people click on. Switch language at the top to fill in the other one.
                 */
                label?: string | null;
                linkType?: ('page' | 'section' | 'custom') | null;
                /**
                 * The link keeps working when this page is renamed or moved.
                 */
                page?: (number | null) | Page;
                /**
                 * Parts of the site that are always there, such as the calendar.
                 */
                section?:
                  | (
                      | 'home'
                      | 'calendar'
                      | 'past-events'
                      | 'news'
                      | 'newsletter'
                      | 'friends-news'
                      | 'podcast'
                      | 'vacancies'
                    )
                  | null;
                /**
                 * Starts with https:// for another website, or with / for an address on this site.
                 */
                url?: string | null;
                /**
                 * Optional. Jumps to one part of the page, for example "volunteers" on the vacancies page.
                 */
                anchor?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * For example the privacy policy.
     */
    legalLinks?:
      | {
          /**
           * The words people click on. Switch language at the top to fill in the other one.
           */
          label?: string | null;
          linkType?: ('page' | 'section' | 'custom') | null;
          /**
           * The link keeps working when this page is renamed or moved.
           */
          page?: (number | null) | Page;
          /**
           * Parts of the site that are always there, such as the calendar.
           */
          section?:
            | ('home' | 'calendar' | 'past-events' | 'news' | 'newsletter' | 'friends-news' | 'podcast' | 'vacancies')
            | null;
          /**
           * Starts with https:// for another website, or with / for an address on this site.
           */
          url?: string | null;
          /**
           * Optional. Jumps to one part of the page, for example "volunteers" on the vacancies page.
           */
          anchor?: string | null;
          id?: string | null;
        }[]
      | null;
    showNewsletter?: boolean | null;
  };
  newsletter?: {
    /**
     * People who confirm their email are added to this list in Brevo. You find the number in Brevo under Contacts, Lists, in the column "ID".
     */
    brevoListId?: number | null;
    heading?: string | null;
    intro?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    /**
     * A link to the privacy policy is added after this text automatically.
     */
    consentText?: string | null;
    /**
     * Shown right after someone signs up, in place of the box.
     */
    thanksTitle?: string | null;
    /**
     * Tell people to look in their inbox for the confirmation email.
     */
    thanksMessage?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Shown on the page people land on when they click the link in the email.
     */
    confirmedTitle?: string | null;
    confirmedMessage?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  calendar?: {
    intro?: string | null;
    /**
     * Visitors can always switch. The list reads best on a phone.
     */
    defaultView?: ('list' | 'month') | null;
    /**
     * Shows a button that adds all your events to their own Google, Apple or Outlook calendar and keeps them up to date.
     */
    showSubscribe?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('super-admin' | 'user')[];
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'editor')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * What people filled in. Only people who work on this site can read them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'past-events';
        value: number | PastEvent;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: number | Vacancy;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  parent?: T;
  path?: T;
  body?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        eventsCalendarPreview?: T | EventsCalendarPreviewBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        documents?: T | DocumentsBlockSelect<T>;
        podcast?: T | PodcastBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        item?: T | ItemBlockSelect<T>;
      };
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  background?: T;
  layout?: T;
  headline?: T;
  tagline?: T;
  actions?:
    | T
    | {
        label?: T;
        type?: T;
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        link?: T;
        id?: T;
      };
  image?:
    | T
    | {
        src?: T;
        alt?: T;
        videoUrl?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarPreviewBlock_select".
 */
export interface EventsCalendarPreviewBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  mode?: T;
  eventType?: T;
  events?: T;
  count?: T;
  showMiniCalendar?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  background?: T;
  text?: T;
  url?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  items?:
    | T
    | {
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  stats?:
    | T
    | {
        stat?: T;
        type?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  actions?:
    | T
    | {
        label?: T;
        type?: T;
        icon?:
          | T
          | {
              name?: T;
              color?: T;
              style?: T;
            };
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  background?: T;
  width?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  description?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  background?: T;
  color?: T;
  url?: T;
  caption?: T;
  poster?: T;
  autoPlay?: T;
  loop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  background?: T;
  image?:
    | T
    | {
        src?: T;
        alt?: T;
      };
  content?: T;
  layout?: T;
  imageSize?: T;
  verticalAlignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  source?: T;
  images?: T;
  pastEvent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DocumentsBlock_select".
 */
export interface DocumentsBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  files?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PodcastBlock_select".
 */
export interface PodcastBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  mode?: T;
  count?: T;
  episodes?:
    | T
    | {
        match?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  intro?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemBlock_select".
 */
export interface ItemBlockSelect<T extends boolean = true> {
  background?: T;
  title?: T;
  images?: T;
  details?: T;
  priceText?: T;
  actionType?: T;
  buttonLabel?: T;
  linkUrl?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  status?: T;
  statusNote?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  eventType?: T;
  location?:
    | T
    | {
        address?: T;
        mapsLink?: T;
        callLink?: T;
      };
  image?: T;
  speakers?:
    | T
    | {
        speaker?: T;
        role?: T;
        id?: T;
      };
  registrationLink?: T;
  featured?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-events_select".
 */
export interface PastEventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  heroImg?: T;
  excerpt?: T;
  author?: T;
  date?: T;
  relatedEvent?: T;
  tags?: T;
  photos?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        documents?: T | DocumentsBlockSelect<T>;
        podcast?: T | PodcastBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        item?: T | ItemBlockSelect<T>;
      };
  body?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  type?: T;
  organization?: T;
  publishDate?: T;
  tags?: T;
  externalLink?: T;
  linkDescription?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  body?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        documents?: T | DocumentsBlockSelect<T>;
        podcast?: T | PodcastBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        item?: T | ItemBlockSelect<T>;
      };
  featured?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  language?: T;
  opportunityType?: T;
  location?:
    | T
    | {
        type?: T;
        cityRegion?: T;
      };
  startDate?: T;
  duration?: T;
  openApplication?: T;
  applicationDeadline?: T;
  description?: T;
  responsibilities?: T;
  requiredSkills?: T;
  preferredQualities?: T;
  languagesRequired?: T;
  compensation?:
    | T
    | {
        details?: T;
      };
  accessibilityNotes?: T;
  howToApply?: T;
  contactInfo?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  supportingDocument?: T;
  valuesStatement?: T;
  openToNontraditional?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  avatar?: T;
  affiliation?: T;
  bio?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  avatar?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  from?: T;
  to?: T;
  permanent?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  general?:
    | T
    | {
        name?: T;
        tagline?: T;
        logo?: T;
        contact?:
          | T
          | {
              address?: T;
              email?: T;
              phone?: T;
            };
        social?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  header?:
    | T
    | {
        nav?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              section?: T;
              url?: T;
              anchor?: T;
              highlight?: T;
              children?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    page?: T;
                    section?: T;
                    url?: T;
                    anchor?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    page?: T;
                    section?: T;
                    url?: T;
                    anchor?: T;
                    id?: T;
                  };
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              section?: T;
              url?: T;
              anchor?: T;
              id?: T;
            };
        showNewsletter?: T;
      };
  newsletter?:
    | T
    | {
        brevoListId?: T;
        heading?: T;
        intro?: T;
        placeholder?: T;
        buttonLabel?: T;
        consentText?: T;
        thanksTitle?: T;
        thanksMessage?: T;
        confirmedTitle?: T;
        confirmedMessage?: T;
      };
  calendar?:
    | T
    | {
        intro?: T;
        defaultView?: T;
        showSubscribe?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteUrl?: T;
  revalidateSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}