// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: pnpm generate:pathnames
// Source: scripts/generate-pathnames.ts
// Last generated: 2026-02-03T11:17:08.982Z

import { defineRouting } from 'next-intl/routing';

export const routing = defineRouting({
    locales: ['en', 'nl'],
    defaultLocale: 'en',
    pathnames: {
        '/': "/",
        '/about-us/history': "/about-us/history",
        '/about-us': "/about-us",
        '/about-us/network': "/about-us/network",
        '/about-us/what-is-boerengroep': "/about-us/what-is-boerengroep",
        '/about-us/who-are-we': "/about-us/who-are-we",
        '/accessibility': "/accessibility",
        '/activities/auditorium': "/activities/auditorium",
        '/activities/calendar-sections/breaks': "/activities/calendar-sections/breaks",
        '/activities/calendar-sections/open-meetings': "/activities/calendar-sections/open-meetings",
        '/activities/calendar-sections/soup-kitchen': "/activities/calendar-sections/soup-kitchen",
        '/activities/fei': "/activities/fei",
        '/activities/forum-reader': "/activities/forum-reader",
        '/activities/group-studies': "/activities/group-studies",
        '/activities': "/activities",
        '/activities/reclaim-the-seeds': "/activities/reclaim-the-seeds",
        '/activities/soup-kitchen': "/activities/soup-kitchen",
        '/activities/teachers': "/activities/teachers",
        '/contact': "/contact",
        '/cookies': "/cookies",
        '/inspringtheater': "/inspringtheater",
        '/library/agroecologie-netwerk': "/library/agroecologie-netwerk",
        '/library/archive': "/library/archive",
        '/library': "/library",
        '/library/media': "/library/media",
        '/library/podcast': "/library/podcast",
        '/news/friends-news': "/news/friends-news",
        '/news/newsletter': "/news/newsletter",
        '/privacy-policy': "/privacy-policy",
        '/terms-conditions': "/terms-conditions",
        '/vacancies': "/vacancies",
        '/activiteiten/agenda-secties/breaks': "/activiteiten/agenda-secties/breaks",
        '/activiteiten/agenda-secties/open-meetings': "/activiteiten/agenda-secties/open-meetings",
        '/activiteiten/agenda-secties/soup-kitchen': "/activiteiten/agenda-secties/soup-kitchen",
        '/activiteiten/auditorium': "/activiteiten/auditorium",
        '/activiteiten/docenten': "/activiteiten/docenten",
        '/activiteiten/fei': "/activiteiten/fei",
        '/activiteiten/forumlezer': "/activiteiten/forumlezer",
        '/activiteiten/groepsstudies': "/activiteiten/groepsstudies",
        '/activiteiten': "/activiteiten",
        '/activiteiten/reclaim-the-seeds': "/activiteiten/reclaim-the-seeds",
        '/activiteiten/soepkeuken': "/activiteiten/soepkeuken",
        '/algemene-voorwaarden': "/algemene-voorwaarden",
        '/bibliotheek/agroecologie-netwerk': "/bibliotheek/agroecologie-netwerk",
        '/bibliotheek/archief': "/bibliotheek/archief",
        '/bibliotheek': "/bibliotheek",
        '/bibliotheek/media': "/bibliotheek/media",
        '/bibliotheek/podcast': "/bibliotheek/podcast",
        '/nieuws/friends-news': "/nieuws/friends-news",
        '/nieuws/newsletter': "/nieuws/newsletter",
        '/over-ons/geschiedenis': "/over-ons/geschiedenis",
        '/over-ons': "/over-ons",
        '/over-ons/netwerk': "/over-ons/netwerk",
        '/over-ons/wat-is-boerengroep': "/over-ons/wat-is-boerengroep",
        '/over-ons/wie-zijn-wij': "/over-ons/wie-zijn-wij",
        '/vacatures': "/vacatures"
}
});

export const PATHNAMES = {
    HOME: '/',
    ABOUT_US: '/about-us',
    ACTIVITIES: '/activities',
    VACANCIES: '/vacancies',
    NEWS: '/news',
    INSPIRATION_THEATER: '/inspiration-theater',
    LIBRARY: '/library',
    CONTACT: '/contact'
} as const;
