query pageQuery {
    ...LayoutQueryFragment
    postConnection {
        edges {
            node {
                id
                date
                title
                excerpt
                author {
                    ... on Author {
                        ...AuthorParts
                    }
                }
                _sys {
                    filename
                }
            }
        }
    }
}

query contentQuery($relativePath: String!) {
    ...LayoutQueryFragment
    page(relativePath: $relativePath) {
        ...PageParts
    }
}

query blogPostQuery($relativePath: String!) {
    ...LayoutQueryFragment
    post(relativePath: $relativePath) {
        ...PostParts
        author {
            ... on Author {
                name
                avatar
            }
        }
    }
}

query calendarQuery {
    eventConnection {
        edges {
            node {
                id
                title
                description
                startDate
                endDate
                eventType
                location {
                    address
                    mapsLink
                    callLink
                }
                speakers {
                    speaker {
                        ... on Speaker {
                            id
                            name
                            avatar
                            affiliation
                        }
                    }
                    role
                }
                featured
                _sys {
                    filename
                    basename
                    breadcrumbs
                    path
                    relativePath
                }
            }
        }
    }
}

query vacancyQuery {
    ...LayoutQueryFragment
    vacancyConnection {
        edges {
            node {
                id
                opportunityType
                title
                location {
                    type
                    cityRegion
                }
                startDate
                duration
                applicationDeadline
                description
                responsibilities
                requiredSkills
                preferredQualities
                languagesRequired
                compensation {
                    details
                }
                accessibilityNotes
                howToApply
                contactInfo {
                    name
                    email
                    phone
                }
                supportingDocument
                valuesStatement
                openToNontraditional
                _sys {
                    filename
                    basename
                    breadcrumbs
                    path
                    relativePath
                }
            }
        }
    }
}

query newsletterQuery($relativePath: String!) {
    ...LayoutQueryFragment
    newsletter(relativePath: $relativePath) {
        id
        title
        type
        organization
        publishDate
        tags
        externalLink
        linkDescription
        author {
            ... on Speaker {
                name
                avatar
                affiliation
            }
        }
        featuredImage
        excerpt
        body {
            __typename
            ... on NewsletterBodyHero {
                headline
                tagline
                actions {
                    label
                    type
                    link
                    icon {
                        name
                        color
                        style
                    }
                }
                image {
                    src
                    alt
                    videoUrl
                }
            }
            ... on NewsletterBodyContent {
                body
            }
            ... on NewsletterBodyFeatures {
                title
                description
                items {
                    title
                    text
                    icon {
                        name
                        color
                        style
                    }
                }
            }
            ... on NewsletterBodyTestimonial {
                title
                description
                testimonials {
                    quote
                    author
                    role
                    avatar
                }
            }
            ... on NewsletterBodyVideo {
                color
                url
                autoPlay
                loop
            }
            ... on NewsletterBodyCallout {
                text
                url
            }
            ... on NewsletterBodyStats {
                title
                description
                stats {
                    stat
                    type
                }
            }
            ... on NewsletterBodyCta {
                title
                description
                actions {
                    label
                    type
                    link
                    icon {
                        name
                        color
                        style
                    }
                }
            }
            ... on NewsletterBodyImageText {
                image {
                    src
                    alt
                }
                content
                layout
                imageSize
                verticalAlignment
            }
        }
        featured
        published
        _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
        }
    }
}

query newsletterConnectionQuery {
    newsletterConnection {
        edges {
            node {
                id
                title
                type
                organization
                publishDate
                tags
                externalLink
                linkDescription
                author {
                    ... on Speaker {
                        name
                        avatar
                        affiliation
                    }
                }
                featuredImage
                excerpt
                featured
                published
                _sys {
                    filename
                    basename
                    breadcrumbs
                    path
                    relativePath
                }
            }
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
    }
}
